[embeddings]
embeddings_function = "all-MiniLM-L6-v2"
collection_name = "notes_collection"
embeddings_path = "./embeddings"

[files]
markdown_directory = "/home/funinkina/Notes/"
state_file = "./.state.json"

[llm]
model_name = "llama3-8b-8192"