[embeddings]
embeddings_function = "all-MiniLM-L6-v2"
collection_name = "notes_collection"
embeddings_path = "/home/funinkina/Notes/.embeddings"

[files]
markdown_directory = "/home/funinkina/Notes/"
state_file = "/home/funinkina/Notes/.state.json"

[state_tracking]
# choose "mtime" if you are not tracking changes with git
method = "git"  # Options: "mtime", "git"

[llm]
provider = "ollama" # Options: "groq" or "openai" or "ollama"
model_name = "gemma3:12b"
# model_name = "gpt-4o"
temperature = 0.5
additonal_info = "True"